### ISSUE TITLE
How to use it need some help

### ISSUE THREAD

**Issue by JACK-ARRAY** [10up/elasticpress-autosuggest#12]
I configured it as mentioned, but no autosuggest, so i need more clarification. here is code i pasted in my nginx
# Elasticsearch endpoint
    location /es-search {

        # only allow things to hit the _autosuggest API
        # change the `_endpoint` to be whatever you'd like to restrict usage to
        location ~* (.*)_suggest$ {
      
            # only allow POST requests
            limit_except POST {
                deny all;
            }
        
            # Perform our request
            rewrite ^/es-search(.*) $1 break;
            proxy_set_header Host $host;

            # Use the URL of the server here
            proxy_pass http://localhost:9200;
        }

        return 403;
    }  

I want to know what is _endpoint

**Comment by tlovett1** [comment]
Hey @JACK-ARRAY this feature has been merged into ElasticPress core for 2.4. Can you test over there?

**Comment by JACK-ARRAY** [comment]
Sir, i am using Elasticpress version 2.3.2. Can you give me link to download version 2.4. When i used elasticpress-autosuggest, a new feature added in core "Autosuggest". I enabled it and clicked on save. It builded index but no autosuggest in site.

**Comment by tlovett1** [comment]
It's in the develop branch of the ElasticPress plugin.

**Comment by JACK-ARRAY** [comment]
I used autosuggest branch but their is issue, i am attaching screenshot
`https://i.imgur.com/m7Cff1R.png`
